import { Inter } from "next/font/google";
import styles from "./layout.module.css";
import Header from "@/components/UI/header";
import Footer from "@/components/UI/footer";
import { cookies } from "next/headers"

import { users } from "@/components/logical/data";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// access a user


export default function RootLayout({ children }) {
  const cookie = cookies();
  const UID =cookie.get("UID")?.value 

  const userProfile  = users.find((user)=> (
      JSON.stringify(user.id) ===  UID
  ))
  return (
    <html lang="en">
      
      
      <body className={inter.className}>
        <main className={styles.mainLayout}>
          
          <div className={styles.header}>
            <Header user ={userProfile}/>
          </div>
          <div className={styles.body}>
            {children}
          </div>
          <div className={styles.footer}>
            <Footer/>
          </div>
          
        </main>
      </body>
      
    </html>
  );
}
